<?php

namespace AppBundle\Repository;

/**
 * BesoinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BesoinRepository extends \Doctrine\ORM\EntityRepository
{ 
	public function findAllOrderedById()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM AppBundle:Besoin p ORDER BY p.id desc'
            )
            ->getResult();
    }
}